version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      major-updates:
        update-types:
          - major
      minor-patch-updates:
        update-types:
          - minor
          - patch
