name: 🔥 Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Firebase Hosting 🚀
    environment: prd
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version info

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.vite
            .svelte-kit
          key: pr-build-${{ runner.os }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            pr-build-${{ runner.os }}-

      - name: Create Sentry environment file
        run: |
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" > .env.sentry-build-plugin
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
       
      - name: Build project with Sentry
        run: pnpm run build
        env:
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ENVIRONMENT: production
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          
      - name: Deploy to main
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHELM }}
          projectId: githelm
          channelId: live